name: Osx

on:
  push:
    branches:
    - master

jobs:
  build_Osx_Catalina:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: Install OpenGL lib  / Requirement for Glfw3
      run : brew update
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Release
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ImGuiFontStudio_Osx.app
        path: build/ImGuiFontStudio_Osx.app
