name: Master Branch build (Linux)

on:
  push:
    branches:
    - master

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: Install OpenGL lib  / Requirement for Glfw3
      run : sudo apt-get update && sudo apt-get install libgl1-mesa-dev libx11-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Release
    - name: install
      run: cmake --install
    - name: create package as artifact
      uses: actions/upload-artifact@v1
      with:
        name: ImGuiFontStudio_Linux
        path: ImGuiFontStudio_Linux
